theme: jekyll-theme-hacker
title: Kyle Kan's Computer Science World (CS-499-X6398 21EW6)
description: Details on Artifacts of Different Projects\nPlease view [README](https://github.com/sacruffnex/CS_Capstone/blob/main/README.md) for instructions on how to use each artifact
